# Generated by Django 4.2.7 on 2023-11-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url_fields',
            new_name='url_field',
        ),
    ]
