# Generated by Django 4.2.7 on 2023-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_rename_url_fields_item_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
